# This is the network config written by 'subiquity'
network:
  ethernets:
    enp3s0:
      addresses:
      - 192.168.3.200/24
      dhcp6: true
      gateway4: 192.168.3.254
      nameservers:
        addresses:
        - 8.8.8.8
        search:
        - localdomain
    enp5s0:
      dhcp4: true
  version: 2
